### ISSUE TITLE
Create PendulumPay first version

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/vortex#1]
### Context
As a first version of PendulumPay,
### Tasks

- [ ] Fork the [portal](https://portal.pendulumchain.org/pendulum/dashboard)
- [ ] Remove option for network selection. Default to Pendulum chain
- [ ] On the left navigation bar, only show the below (remove the rest):
   - [ ] Dashboard
   - [ ] Transaction History - greyed out
   - [ ] Address Book - greyed out
   - [ ] Swap - greyed out
   - [ ] Invoice generator - greyed out
- [ ] Remove Spacewalk banner from Dashboard
- [ ] Remove runtime block number from navigation menu
- [ ] Remove Terms, Privacy and Wiki options
- [ ] Keep the social links
- [ ] Add Request a feature in the navigation menu under social icons. Here is the google form [link](https://forms.gle/3Z5HSR6yacrX3FDT8) 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHZtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b9c4a9b2c2fd2d796743958b544a52fd7b4b4c71/image.png)

- [ ] On connect wallet dialogue box, only show Wallet Connect option
- [ ] Replace Pendulum logo with PendulumPay logo (yet to be provided)
- [ ] Add "Send" button next to every token item on the dasboard
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUx2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--64cb32f8f0191b2e0bc082a0bc15e6f1242ffa25/image.png)
